### ISSUE TITLE
bug & vis

### ISSUE THREAD

**Issue by RyanG41** [yd-yin/AISeg3D#1]
Hi,

Thanks for the wonderful job and open-sourced codes!

1. There are bugs or tips: 
In sai3d.py line 261 the function `everything_seg`, the processing for non-scannet++ data seems to false set as `scene0005_01_vh_clean_2.ply`, which should be `f'{args.scene_id}_vh_clean_2.ply'`.
The data format of scannet 2d data should strickly follow the format 0000.jpg/png (note to pad to 4 bits), or bugs would pop out.

2. Is there any visualization code for the segmentation results? Results seem to be per-point-labeling for every instance in each .txt file, but it is rather tough to visualize them.

**Comment by Ly-kc** [comment]
Thank you for your interest and advice! The bug in function `everything_seg` has been resolved. Additionally, we’ve included code for visualization, please check the README for details.

**Comment by Ly-kc** [comment]
Our data loading function require the naming format of data to be the same as in README. You can find details in the function `get_mask_data` in sai3d.py to customize your data naming format.

**Comment by RyanG41** [comment]
Thanks for the timed fixing and reply!
