### ISSUE TITLE
Semantic instance segmentation precision problems on ScanNet200

### ISSUE THREAD

**Issue by tymanab** [yd-yin/AISeg3D#2]
Hi, 
Thanks for sharing this great project.

I'm trying to reproduce semantic instance segmentation results in your paper with a subset of ScanNet200, and currently my result is lower than the original paper. I run this project strictly follow the instruction in README.md, with datasets as follow:
 >scene0011_00,  scene0011_01,  scene0050_00, scene0050_01, scene0050_02, scene0084_00, scene0084_01, scene0084_02, scene0231_00, scene0231_01 , scene0231_02, scene0378_00, scene0378_01, scene0378_02, scene0518_00

and here is my result
| what| average |  
| :--: | :--: |  
| AP | 0.063 |  
| AP_50% | 0.088 |  
| AP_25% | 0.114 |

Could you please give me some advise to improve the results? 
Maybe I should use the complete ScanNet200.

BTW：I found that the sorting method in [here](https://github.com/yd-yin/SAI3D/blob/b3b11f08bdbbf2d20f0306ef8e739271331c63b0/sai3d.py#L41) is incosist with the one used in [sam_auto_generation](https://github.com/yd-yin/SAI3D/blob/b3b11f08bdbbf2d20f0306ef8e739271331c63b0/sam_auto_generation.py#L30) , which will consequently lead to loading different file index when VIEW_FREQ is not 1 on ubuntu. It will be better if these two place could use same logic.

**Comment by Ly-kc** [comment]
Thanks for your interest!

I just ran openmask3d on the 15 scenes that you used,  and got the following results: 
| What     | Average |
| ----------- | ----------- |
| AP     | 0.130       |
| AP50   | 0.206        |
| AP25   |   0.277      |

It indicates that your results is abnormally low. I think you should rechcek the resolution of your data(including color images, depth images and intrinsic_color) and the configuration of OpenMask3D:
1. You should adjust the [intrinsic_resolution in OpenMask3D configuration](https://github.com/OpenMask3D/openmask3d/blob/main/openmask3d/configs/openmask3d_scannet200_eval.yaml#L9) to make it consist with the resolution of your `intrinsic_color.txt`. 
2. Don't forget to change [this line in OpenMask3D](https://github.com/OpenMask3D/openmask3d/blob/6488/openmask3d/data/load.py#L73) as noted in our README.

Hopefully you can get the desired results.

**Comment by Ly-kc** [comment]
The sorting(and filtering) method has been unified.

**Comment by tymanab** [comment]
Thanks for your reply. 
Everything works well after I aligned the resolution.

**Comment by tymanab** [comment]
Hi,
Could you share you script or provide some details about parsing Scannet and align color/depth image ? 

Currently I'm using the [Python SensReader](https://github.com/ScanNet/ScanNet/tree/master/SensReader/python) provide by ScanNet, and the original size of image generated from it is 1296x968(color) and 640x480(depth).  I resize the color images to depth size and apply colorToDepthExtrinsics to align those images. I'm not sure is this the proper ways to preprocess scannet data for this project.

**Comment by Ly-kc** [comment]
Hi.

I'm using the image of original size (1296x968(color) and 640x480(depth) ), together with the intrinsic of the same resolution as images. I didn't resize the images and intrinsics when preprocessing the dataset. Instead I just change their resolution when loading them in OpenMask3D (as was said in the reply above, change the configuration and the loading function).

 So it's supposed to be OK to use the original data in this project. You can track the variable `resolution` [here](https://github.com/OpenMask3D/openmask3d/blob/main/openmask3d/mask_features_computation/features_extractor.py#L34) and the loaded color image [here](https://github.com/OpenMask3D/openmask3d/blob/main/openmask3d/mask_features_computation/features_extractor.py#L161) to see what's going on in OpenMask3D.
