### ISSUE TITLE
About GT label

### ISSUE THREAD

**Issue by RyanG41** [yd-yin/AISeg3D#3]
Hi,

Thanks for the continuing amendaments to the repo.

I'd like to ask some details about your class-agnostic gt labels. 
1. How did you make the gt txt files? Is it just simply removing the points representing wall and floor in the original ScanNet official semantic gt labels?
2. The gt txt file also seems to be in a per-point-labeling format. Is the order in the txt file consistent with those which I loaded the original clean mesh (for example, using trimesh library)? 
3. Does each one label (one unique number) in the gt txt representing an instance? If so, does the label "0" represent the removed wall and floor?

Best Regards

**Comment by Ly-kc** [comment]
Hi, 

Your questions should be answered together.
Assuming there's N points in a scene, then the gt file `scene_id.txt` should contain N lines representing N points, in the order consistent with those loaded from the original clean mesh. And each line contains an number calculated with the formula: `Number = object_id + 1000*label_id`, where `object_id` indicates the id of the object containing this point and `label_id` indicates the id of semantic label of the object (As for the mapping between semantic label and label_id, please refer to `scannetv2-labels.combined.tsv` in dataset). For example, a window is the 3th object in the scene, and the label_id of "window" is 9, then the points covered by the object will have Number=3+9*1000=9003, which will appear in corresponding lines of gt file.

For points with no object covering them, we set their Number to 0 (or some number lower than 1000, that doesn't matter). **We will filter out invalid points with invalid label_id in evaluation script** (Note that `label_id=int(Number/1000)`), including those with label="wall","floor"... Please refer to [here](https://github.com/yd-yin/SAI3D/blob/master/evaluation/evaluate_class_agnostic_instance.py#L58-L64).

Hopefully you can find my reply helpful.

**Comment by RyanG41** [comment]
Thanks for your detailed explanation. It really helps.
