### ISSUE TITLE
inference time for a single scenes.

### ISSUE THREAD

**Issue by zyrant** [yd-yin/AISeg3D#7]
Hi

Thank you for your work, I would like to know the inference time of a single scenario.

best wishes.

**Comment by Ly-kc** [comment]
Hi,

Thanks for your interest!

I remenber it takes about 20 seconds to get class-agnostic masks of a single scene in ScanNet(using 10% 2D frames). And assigning semantic label for all class-agnostic masks in one scene with OpenMask3D takes 3-5 minutes on single RTX3090.

Note that the number of frames, the granularity and the scale of the scene will affect the running time.

Hopefully you can find it helpful.

**Comment by zyrant** [comment]
Thx for your reply!  I have known about the inference time.

Wish you have a nice day!
